import type { LessonConfig } from "@/lib/curriculum/types";

export const FOUNDATION_INTERVALS = ["m2", "M2", "m3", "M3", "P4", "P5", "P8"] as const;
export const FOUNDATION_TRIADS = ["major", "minor", "augmented", "diminished"] as const;

export const FOUNDATION_LESSONS: LessonConfig[] = [
  {
    slug: "seconds",
    title: "Major and minor seconds",
    exerciseType: "interval-identification",
    intervals: ["m2", "M2"],
    presentation: ["ascending", "descending", "harmonic"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "thirds",
    title: "Major and minor thirds",
    exerciseType: "interval-identification",
    intervals: ["m3", "M3"],
    presentation: ["ascending", "descending", "harmonic"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "seconds-and-thirds",
    title: "Seconds and thirds",
    exerciseType: "interval-identification",
    intervals: ["m2", "M2", "m3", "M3"],
    presentation: ["ascending", "descending", "harmonic"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "through-the-octave",
    title: "Through the octave",
    exerciseType: "interval-identification",
    intervals: ["m2", "M2", "m3", "M3", "P4", "P5", "P8"],
    presentation: ["ascending", "descending", "harmonic"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 84 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "major-minor-triads",
    title: "Major and minor triads",
    exerciseType: "chord-identification",
    qualities: ["major", "minor"],
    presentation: ["harmonic", "melodicAscending", "melodicDescending"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "add-augmented",
    title: "Add augmented",
    exerciseType: "chord-identification",
    qualities: ["major", "minor", "augmented"],
    presentation: ["harmonic", "melodicAscending", "melodicDescending"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
  {
    slug: "four-triads",
    title: "Four triads",
    exerciseType: "chord-identification",
    qualities: ["major", "minor", "augmented", "diminished"],
    presentation: ["harmonic", "melodicAscending", "melodicDescending"],
    inversions: [0],
    voicing: ["closed"],
    pitchRange: { min: 48, max: 72 },
    questions: 10,
    stimulus: ["audio", "staff", "piano"],
  },
];
